import * as fs from 'fs';
import * as path from 'path';

export const RUNTIME_ENV_FILE = 'runtime.env';

export type DebugHubEnv = {
    DEBUGHUB_ENABLED?: string;
    DEBUGHUB_SESSION?: string;
    DEBUGHUB_ENDPOINT?: string;
};

export function runtimeEnvPath(debughubDir: string): string {
    return path.join(debughubDir, RUNTIME_ENV_FILE);
}

export function writeRuntimeEnvFile(debughubDir: string, sessionId: string, endpoint: string): string {
    const envFile = runtimeEnvPath(debughubDir);
    const content = [
        '# Generated by `debughub start`.',
        '# Restart your IntelliJ run configuration after this file changes.',
        `DEBUGHUB_ENABLED=1`,
        `DEBUGHUB_SESSION=${sessionId}`,
        `DEBUGHUB_ENDPOINT=${endpoint}`,
        '',
    ].join('\n');

    fs.writeFileSync(envFile, content, 'utf-8');
    return envFile;
}

export function readRuntimeEnvFile(filePath: string): DebugHubEnv {
    const env: DebugHubEnv = {};
    const content = fs.readFileSync(filePath, 'utf-8');

    for (const line of content.split(/\r?\n/)) {
        const trimmed = line.trim();
        if (trimmed.length === 0 || trimmed.startsWith('#')) {
            continue;
        }

        const separatorIndex = trimmed.indexOf('=');
        if (separatorIndex === -1) {
            continue;
        }

        const key = trimmed.slice(0, separatorIndex).trim();
        const rawValue = trimmed.slice(separatorIndex + 1).trim();
        const value = unquoteEnvValue(rawValue);

        if (key === 'DEBUGHUB_ENABLED' || key === 'DEBUGHUB_SESSION' || key === 'DEBUGHUB_ENDPOINT') {
            env[key] = value;
        }
    }

    return env;
}

function unquoteEnvValue(value: string): string {
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith('\'') && value.endsWith('\''))) {
        return value.slice(1, -1);
    }

    return value;
}
